### ISSUE TITLE
Change an individual worker's shift

### ISSUE THREAD

**Issue by ThomFish** [tapegram/wc-app#73]
Ideally this would look like drag and drop a worker to a new area of the wallchart (something like [this](https://htmldom.dev/drag-and-drop-table-row/)?)

Just something to make this more usable since worker shifts change.

**Comment by tapegram** [comment]
I'm down to try drag and drop but I'd prefer not to implement it ourselves since its kinda hard and finicky. My preference would be to start with some kind of drop down to allow moving to a different shift/location/etc. on the worker detail page since that *should* be easy to do.

Also, in the spirit of immutable data, we will likely want to re-evaluate our models to make sure we have a built-in history of where a worker has been previously. This will be very very cool in the future when we start building reports and trying to extract any kind of insight

**Comment by ThomFish** [comment]
A dropdown would definitely be easier. Would it be something like a graphql query that takes a workerId and returns the shift assignments for that worker? Maybe something like below? I was messing with chatGPT and it spit this out (which I edited a lil). I'm pretty sure there's an error in the query but I am not good enough with graphql to figure it out. 

`import React, { useState } from "react";
import { useQuery, useMutation } from "@apollo/client";
import { gql } from "@apollo/client";

const QUERY = gql`
  query EditShiftAssignmentById($id: Int!) {
    shiftAssignment: shiftAssignment(id: $id) {
      id
      workerId
      shiftId
    }
  }
`;
const UPDATE_SHIFT_ASSIGNMENT_MUTATION = gql`
  mutation UpdateShiftAssignmentMutation(
    $id: Int!
    $input: UpdateShiftAssignmentInput!
  ) {
    updateShiftAssignment(id: $id, input: $input) {
      id
      workerId
      shiftId
    }
  }
`;

interface Props {
  workerId: number;
}

const ShiftAssignmentDropdown: React.FC<Props> = ({ workerId }) => {
  const [selectedShift, setSelectedShift] = useState(null);
  const { loading, error, data } = useQuery(QUERY, {
    variables: { id: workerId },
  });
  const [updateShiftAssignment] = useMutation(UPDATE_SHIFT_ASSIGNMENT_MUTATION);

  if (loading) return <progress className="progress w-56"></progress>;
  if (error) return <p>Error</p>;

  const handleChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    setSelectedShift(event.target.value);
  };

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    updateShiftAssignment({
      variables: {
        id: workerId,
        input: { shiftId: selectedShift },
      },
    });
  };

  return (
    <form onSubmit={handleSubmit}>

      <label>
        Shift Assignments:
        <select value={selectedShift} onChange={handleChange}>
          {data.shiftAssignments.map((shift) => (
            <option key={shift.id} value={shift.id}>
              {shift.shiftId}
            </option>
          ))}
        </select>
      </label>
      <button className="btn btn-ghost" type="submit">Update</button>
    </form>
  );
};

export default ShiftAssignmentDropdown;
`
